from __future__ import annotations

import hashlib
import re
from pathlib import Path


FINAL_RENDER_BLOCK = r'''def figure_block(temp_dir: Path, figures: list[Figure], prefix: str) -> str:
    blocks: list[str] = []
    for index, figure in enumerate(figures, 1):
        filename = write_data_uri_figure(temp_dir, figure, f"{prefix}_{index:03d}")
        if not filename:
            continue
        caption = tex_escape(compact_text(figure.alt or ""))
        caption_tex = f"\n{{\\footnotesize\\itshape {caption}\\par}}" if caption else ""
        blocks.append(
            "\\begin{center}\n"
            f"% Image file is generated by the PDF service from the worksheet payload.\n"
            f"\\includegraphics[width=0.78\\linewidth,height=0.30\\textheight,keepaspectratio]{{{filename}}}"
            f"{caption_tex}\n"
            "\\end{center}\n"
        )
    return "".join(blocks)


def statement_blocks(problem: WorksheetProblem, options: WorksheetOptions) -> str:
    ru = tex_escape(problem.statement or "")
    de = tex_escape(problem.statementOriginal or "")
    if options.language == "de" and de:
        return de
    if options.language == "both" and de:
        return (
            "\\textbf{Русский перевод.}\\par\n"
            f"{ru}\n\n"
            "\\textbf{Оригинал.}\\par\n"
            f"{de}"
        )
    return ru


def meta_line(problem: WorksheetProblem) -> str:
    bits: list[str] = []
    if problem.sourceProblemNumber:
        bits.append(f"№ {compact_text(problem.sourceProblemNumber)}")
    if problem.grade:
        bits.append(f"{', '.join(str(g) for g in problem.grade)} класс")
    if problem.difficulty:
        bits.append(f"сложность {problem.difficulty}")
    return " · ".join(bits)


def tags_line(problem: WorksheetProblem) -> str:
    tags = [*problem.topics, *problem.subtopicLabels, *problem.methods]
    return " · ".join(compact_text(tag) for tag in tags if compact_text(tag))


def workspace_block(space: str) -> str:
    heights = {
        "small": "28mm",
        "medium": "50mm",
        "large": "82mm",
    }
    if space not in heights:
        return ""
    return (
        "\\par\\vspace{2mm}\n"
        f"\\noindent\\rule{{\\linewidth}}{{0.2pt}}\\par\\vspace{{{heights[space]}}}\n"
    )


def render_problem(
    temp_dir: Path,
    problem: WorksheetProblem,
    number: int,
    options: WorksheetOptions,
) -> str:
    title = tex_escape(problem.title or "Задача")
    source = tex_escape(problem.sourceName or "")
    meta = tex_escape(meta_line(problem))
    body = [
        "\\Needspace{8\\baselineskip}\n",
        f"\\problem{{{number}}}{{{title}}}\n",
    ]
    if meta:
        body.append(f"{{\\footnotesize\\itshape {meta}\\par}}\n")
    if options.showSources and source:
        body.append(f"{{\\footnotesize\\itshape {source}\\par}}\n")
    body.append(statement_blocks(problem, options))
    body.append("\n")
    if options.includeFigures:
        body.append(figure_block(temp_dir, problem.figures, f"p{number}_fig"))
    if options.showTags:
        tags = tex_escape(tags_line(problem))
        if tags:
            body.append(f"{{\\scriptsize\\itshape {tags}\\par}}\n")
    if options.includeAnswers and (problem.answer or problem.answerFigures):
        body.append("\\answerheading\n")
        if problem.answer:
            body.append(tex_escape(problem.answer))
            body.append("\n")
        body.append(figure_block(temp_dir, problem.answerFigures, f"p{number}_answer"))
    if options.includeSolutions and (problem.solution or problem.solutionFigures):
        body.append("\\solutionheading\n")
        if problem.solution:
            body.append(tex_escape(problem.solution))
            body.append("\n")
        body.append(figure_block(temp_dir, problem.solutionFigures, f"p{number}_solution"))
    body.append(workspace_block(options.space))
    body.append("\n")
    return "".join(body)


def render_tex(temp_dir: Path, request: BuildPdfRequest) -> str:
    options = request.options
    columns = 2 if int(options.columns or 1) == 2 else 1
    title = tex_escape(compact_text(request.title) or "Листок задач")
    subtitle = tex_escape(compact_text(request.subtitle or ""))
    rendered_problems = [
        render_problem(temp_dir, problem, index, options)
        for index, problem in enumerate(request.problems, 1)
    ]
    body = "\n".join(rendered_problems)
    if columns == 2:
        body = "\\begin{multicols}{2}\n" + body + "\n\\end{multicols}\n"
    subtitle_tex = f"{{\\centering\\large {subtitle}\\par}}" if subtitle else ""
    return rf"""\documentclass[11pt,a4paper]{{article}}
\usepackage[a4paper,left=18mm,right=18mm,top=16mm,bottom=18mm]{{geometry}}
\usepackage{{fontspec}}
\setmainfont{{DejaVu Serif}}
\setsansfont{{DejaVu Sans}}
\usepackage{{polyglossia}}
\setdefaultlanguage{{russian}}
\setotherlanguage{{german}}
\usepackage{{graphicx}}
\usepackage{{enumitem}}
\usepackage{{multicol}}
\usepackage{{needspace}}
\usepackage{{hyperref}}
\hypersetup{{colorlinks=false,pdfborder={{0 0 0}}}}
\setlength{{\parindent}}{{0pt}}
\setlength{{\parskip}}{{0.55em}}
\setlength{{\columnsep}}{{9mm}}
\setlist{{nosep}}
\newcommand{{\problem}}[2]{{%
  \par\medskip
  \noindent\textbf{{Задача #1.}}\quad\textbf{{#2}}\par\nobreak
}}
\newcommand{{\answerheading}}{{\par\smallskip\noindent\textit{{Ответ.}}\quad}}
\newcommand{{\solutionheading}}{{\par\smallskip\noindent\textit{{Решение.}}\quad}}
\begin{{document}}
{{\centering\LARGE\bfseries {title}\par}}
{subtitle_tex}
\vspace{{2mm}}
\hrule
\vspace{{5mm}}
{body}
\end{{document}}
"""


'''

BUILD_TEX_ENDPOINT = r'''

@app.post("/build-tex")
def build_tex(request: BuildPdfRequest) -> Response:
    safe_problem_limit(request.problems)
    with tempfile.TemporaryDirectory(prefix="worksheet-tex-") as tmp:
        temp_dir = Path(tmp)
        tex_source = render_tex(temp_dir, request)
    return Response(
        content=tex_source,
        media_type="application/x-tex; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="worksheet.tex"'},
    )
'''

TEX_JS = '''async function worksheetDownloadTex(){if(!worksheetProblems().length){alert('Сначала выберите хотя бы одну задачу.'); return;} let api=worksheetPdfApiUrl(); if(!api){const next=prompt('Адрес PDF-сервера Cloud Run',''); if(next===null)return; worksheetSetPdfApiUrl(next); api=worksheetPdfApiUrl();} if(!api){alert('Сначала укажите адрес PDF-сервера.'); return;} const button=document.querySelector('[data-worksheet-download-tex]'); const oldText=button?button.textContent:''; if(button){button.disabled=true; button.textContent='Собираю TeX...';} try{const res=await fetch(api.replace(/\/+$/,'')+'/build-tex',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(worksheetPdfPayload())}); if(!res.ok){let msg=await res.text(); throw new Error((msg||('HTTP '+res.status)).slice(0,1200));} const blob=await res.blob(); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=worksheetBaseName()+'.tex'; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0); showToast('TeX готов');}catch(err){alert('Не удалось скачать TeX: '+(err&&err.message?err.message:err));}finally{if(button){button.disabled=false; button.textContent=oldText||'Скачать TeX';}}}
'''

HTML_FILES = [
    Path('docs/index.html'),
    Path('docs/admin.html'),
    Path('current_release/olympiad_public_readonly.html'),
    Path('current_release/olympiad_taxonomy_prototype.html'),
]


def replace_between(text: str, start_marker: str, end_marker: str, replacement: str) -> str:
    start = text.index(start_marker)
    end = text.index(end_marker, start)
    return text[:start] + replacement + text[end:]


def patch_app() -> None:
    path = Path('server/tex-pdf-service/app.py')
    text = path.read_text(encoding='utf-8')
    text = replace_between(text, 'def figure_block', '\ndef compile_pdf', FINAL_RENDER_BLOCK)
    if '@app.post("/build-tex")' not in text:
        marker = '    return Response(\n        content=pdf,\n        media_type="application/pdf",\n        headers={"Content-Disposition": \'attachment; filename="worksheet.pdf"\'},\n    )'
        idx = text.index(marker) + len(marker)
        text = text[:idx] + BUILD_TEX_ENDPOINT + text[idx:]
    path.write_text(text, encoding='utf-8')


def patch_html_file(path: Path) -> None:
    text = path.read_text(encoding='utf-8')
    if text.count('data-worksheet-download-tex') < 1:
        html_button = '<button class="btn" data-worksheet-download-html="1">'
        text = text.replace(html_button, '<button class="btn" data-worksheet-download-tex="1">Скачать TeX</button>' + html_button, 1)
    if text.count('data-worksheet-download-tex') < 2:
        text, count = re.subn(
            r'(<button class="btn primary" data-worksheet-download-pdf="1">PDF [^<]*</button>)(</div></div><div id="worksheetPreview")',
            r'\1<button class="btn" data-worksheet-download-tex="1">TeX</button>\2',
            text,
            count=1,
        )
        if count != 1:
            raise SystemExit(f'{path}: preview TeX button target not found')
    if 'async function worksheetDownloadTex()' not in text:
        insert_at = text.index('function worksheetDownloadHtml()')
        text = text[:insert_at] + TEX_JS + text[insert_at:]
    click_old = "if(x=e.target.closest('[data-worksheet-download-pdf]')){worksheetDownloadPdf();return;} if(x=e.target.closest('[data-worksheet-pdf-server]')){worksheetConfigurePdfServer();return;}"
    click_new = "if(x=e.target.closest('[data-worksheet-download-pdf]')){worksheetDownloadPdf();return;} if(x=e.target.closest('[data-worksheet-download-tex]')){worksheetDownloadTex();return;} if(x=e.target.closest('[data-worksheet-pdf-server]')){worksheetConfigurePdfServer();return;}"
    if click_new not in text:
        if click_old not in text:
            raise SystemExit(f'{path}: click handler target not found')
        text = text.replace(click_old, click_new, 1)
    path.write_text(text, encoding='utf-8')


def replace_or_skip(text: str, old: str, new: str, label: str) -> str:
    if new in text:
        return text
    if old not in text:
        raise SystemExit(f'Missing text in {label}')
    return text.replace(old, new, 1)


def patch_docs() -> None:
    readme_path = Path('server/tex-pdf-service/README.md')
    readme = readme_path.read_text(encoding='utf-8')
    readme = replace_or_skip(
        readme,
        'The static site sends structured worksheet JSON to `POST /build-pdf`. The service does not accept raw TeX: it escapes task text, writes selected PNG/JPEG data-URI figures to a temporary directory, generates `worksheet.tex`, and compiles it with `xelatex`.',
        'The static site sends structured worksheet JSON to `POST /build-pdf` or `POST /build-tex`. The service does not accept raw TeX: it escapes task text, writes selected PNG/JPEG data-URI figures to a temporary directory, generates `worksheet.tex`, and either compiles it with `xelatex` or returns the TeX source.',
        'README intro',
    )
    readme = replace_or_skip(
        readme,
        '```bash\ncurl http://localhost:8080/healthz\n```',
        '```bash\ncurl http://localhost:8080/healthz\n```\n\nBuild endpoints:\n\n- `POST /build-pdf` returns `worksheet.pdf`.\n- `POST /build-tex` returns `worksheet.tex`.\n\nThe TeX download is the editable source generated from the same worksheet template. When figures are enabled, the TeX source references generated image filenames; a future TeX bundle export can package those images together with the source.',
        'README endpoints',
    )
    readme_path.write_text(readme, encoding='utf-8')

    doc_path = Path('project_docs/TEX_PDF_SERVER.md')
    doc = doc_path.read_text(encoding='utf-8')
    doc = replace_or_skip(
        doc,
        '3. The server generates a temporary `.tex` file and compiles it with `xelatex`.\n4. The browser receives and downloads `worksheet.pdf`.',
        '3. The server generates a temporary `.tex` file.\n4. For PDF export, the server compiles it with `xelatex` and the browser downloads `worksheet.pdf`.\n5. For TeX export, the browser downloads the generated `worksheet.tex`.',
        'project doc flow',
    )
    doc = replace_or_skip(
        doc,
        'The server does not accept raw TeX. It accepts structured JSON, escapes text, writes selected images to a temporary directory, and compiles the generated TeX. This keeps the public endpoint narrower and safer.',
        'The server does not accept raw TeX. It accepts structured JSON, escapes text, writes selected images to a temporary directory, and then either compiles the generated TeX or returns it as a source file. This keeps the public endpoint narrower and safer.\n\n## Endpoints\n\n- `GET /healthz`: simple health check.\n- `POST /build-pdf`: builds and returns `worksheet.pdf`.\n- `POST /build-tex`: returns the generated `worksheet.tex`.\n\nThe current TeX download is a plain `.tex` file. If figures are enabled, it references the temporary image filenames generated during server-side compilation. A later improvement can add a `.zip` TeX bundle with `worksheet.tex` and image files together.',
        'project doc endpoints',
    )
    doc_path.write_text(doc, encoding='utf-8')


def update_checksums() -> None:
    manifest = Path('checksums.sha256')
    lines = []
    for raw in manifest.read_text(encoding='utf-8').splitlines():
        if not raw.strip():
            continue
        _, rel = raw.split('  ', 1)
        rel = rel.strip().replace('\\', '/')
        digest = hashlib.sha256(Path(rel).read_bytes()).hexdigest()
        lines.append(f'{digest}  {rel}')
    manifest.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def cleanup_temp_files() -> None:
    Path('.github/workflows/codex-tex-download.yml').unlink(missing_ok=True)
    Path('tools/codex_tex_patch.py').unlink(missing_ok=True)


def main() -> None:
    patch_app()
    for html_path in HTML_FILES:
        patch_html_file(html_path)
    patch_docs()
    update_checksums()
    cleanup_temp_files()


if __name__ == '__main__':
    main()
